version: '3.8'

# Definir una red personalizada
networks:
  ventas_network:
    driver: bridge

services:
  backend:
    build: ./back
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - mysql_db
      - postgres_db
      - sqlserver_db
    networks:  # Conectar este servicio a la red
      - ventas_network

  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: ventas_mysql
    volumes:
      - ./DB/mysql:/docker-entrypoint-initdb.d
    networks:
      - ventas_network

  postgres_db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: postgres
    volumes:
      - ./DB/postgres:/docker-entrypoint-initdb.d
    networks:
      - ventas_network

  sqlserver_db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: SqlServer123
      ACCEPT_EULA: Y
    volumes:
      - ./DB/sqlserver:/docker-entrypoint-initdb.d
    networks:
      - ventas_network
      
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - ventas_network