FROM python:3.9-slim

WORKDIR /app

# Instalar dependencias del sistema para pyodbc y otras librerías
RUN apt-get update && \
    apt-get install -y gcc python3-dev unixodbc-dev unixodbc && \
    rm -rf /var/lib/apt/lists/*

# Copiar e instalar dependencias de Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código de la aplicación
COPY . .

ENV FLASK_APP=app
ENV FLASK_ENV=development

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0"]